spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: movieInfo


#  mongodb:
#    embedded:
#      version: 3.2.2

